# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Ramdomized smallest enclosing disk
NULL

#' @param points a numeric matrix with an x and y column, filled with points
NULL

#' @export
NULL

segment_wise_coords <- function(center, path, eps) {
    .Call('_klcluster_segment_wise_coords', PACKAGE = 'klcluster', center, path, eps)
}

center_disk <- function(p1, p2, p3) {
    .Call('_klcluster_center_disk', PACKAGE = 'klcluster', p1, p2, p3)
}

sed_randomized <- function(points) {
    .Call('_klcluster_sed_randomized', PACKAGE = 'klcluster', points)
}

#' Smallest enclosing disc
#'
#' @param points a numeric matrix with an x and y column, filled with points
#'
#' @export
#'
sed <- function(points) {
    .Call('_klcluster_sed', PACKAGE = 'klcluster', points)
}

count_sed <- function(points, times) {
    .Call('_klcluster_count_sed', PACKAGE = 'klcluster', points, times)
}

count_sed_random <- function(points, times) {
    .Call('_klcluster_count_sed_random', PACKAGE = 'klcluster', points, times)
}

get_free_interval_c <- function(avec, uvec, vvec, eps) {
    .Call('_klcluster_get_free_interval_c', PACKAGE = 'klcluster', avec, uvec, vvec, eps)
}

use_interval_c <- function(p1, p2, eps) {
    .Call('_klcluster_use_interval_c', PACKAGE = 'klcluster', p1, p2, eps)
}

check_eps_c <- function(p1_mat, p2_mat, eps) {
    .Call('_klcluster_check_eps_c', PACKAGE = 'klcluster', p1_mat, p2_mat, eps)
}

get_frechet_c <- function(p1_mat, p2_mat, precision) {
    .Call('_klcluster_get_frechet_c', PACKAGE = 'klcluster', p1_mat, p2_mat, precision)
}

dtw <- function(p1, p2, sqr_dist) {
    .Call('_klcluster_dtw', PACKAGE = 'klcluster', p1, p2, sqr_dist)
}

calc_ca <- function(ca, i, j, p1, p2) {
    .Call('_klcluster_calc_ca', PACKAGE = 'klcluster', ca, i, j, p1, p2)
}

get_interval_c <- function() {
    .Call('_klcluster_get_interval_c', PACKAGE = 'klcluster')
}

is_empty_c <- function(xmin, xmax, row, col) {
    .Call('_klcluster_is_empty_c', PACKAGE = 'klcluster', xmin, xmax, row, col)
}

dist_matrix <- function(p1, p2) {
    .Call('_klcluster_dist_matrix', PACKAGE = 'klcluster', p1, p2)
}

get_coord <- function(point1, point2, dist) {
    .Call('_klcluster_get_coord', PACKAGE = 'klcluster', point1, point2, dist)
}

backtrack <- function(center, path, dist_mat) {
    .Call('_klcluster_backtrack', PACKAGE = 'klcluster', center, path, dist_mat)
}

index_shuffle <- function(start, n) {
    .Call('_klcluster_index_shuffle', PACKAGE = 'klcluster', start, n)
}

dist_c <- function(ax, ay, bx, by) {
    .Call('_klcluster_dist_c', PACKAGE = 'klcluster', ax, ay, bx, by)
}

squared_dist <- function(ax, ay, bx, by) {
    .Call('_klcluster_squared_dist', PACKAGE = 'klcluster', ax, ay, bx, by)
}

calc_dot <- function(ax, ay, bx, by) {
    .Call('_klcluster_calc_dot', PACKAGE = 'klcluster', ax, ay, bx, by)
}

coord_wise_mean <- function(coords, nr_coords) {
    .Call('_klcluster_coord_wise_mean', PACKAGE = 'klcluster', coords, nr_coords)
}

calc_dist_c <- function(a, b) {
    .Call('_klcluster_calc_dist_c', PACKAGE = 'klcluster', a, b)
}

subtract_xy_c <- function(u, v) {
    .Call('_klcluster_subtract_xy_c', PACKAGE = 'klcluster', u, v)
}

dot_product_c <- function(a, b) {
    .Call('_klcluster_dot_product_c', PACKAGE = 'klcluster', a, b)
}

dist_point_to_line_c <- function(a, u, v) {
    .Call('_klcluster_dist_point_to_line_c', PACKAGE = 'klcluster', a, u, v)
}

which_min <- function(x) {
    .Call('_klcluster_which_min', PACKAGE = 'klcluster', x)
}

subset_vec <- function(x, index) {
    .Call('_klcluster_subset_vec', PACKAGE = 'klcluster', x, index)
}

get_max <- function(x) {
    .Call('_klcluster_get_max', PACKAGE = 'klcluster', x)
}

get_min <- function(x) {
    .Call('_klcluster_get_min', PACKAGE = 'klcluster', x)
}

get_max2 <- function(x, y) {
    .Call('_klcluster_get_max2', PACKAGE = 'klcluster', x, y)
}

get_min2 <- function(x, y) {
    .Call('_klcluster_get_min2', PACKAGE = 'klcluster', x, y)
}

df1_to_nv <- function(df) {
    .Call('_klcluster_df1_to_nv', PACKAGE = 'klcluster', df)
}

df_to_mat <- function(x) {
    .Call('_klcluster_df_to_mat', PACKAGE = 'klcluster', x)
}

mat_to_df <- function(mat, path) {
    .Call('_klcluster_mat_to_df', PACKAGE = 'klcluster', mat, path)
}

concat_vec <- function(vec1, vec2) {
    .Call('_klcluster_concat_vec', PACKAGE = 'klcluster', vec1, vec2)
}

subset_mat <- function(mat, index) {
    .Call('_klcluster_subset_mat', PACKAGE = 'klcluster', mat, index)
}

